### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by bmeverett** [emmysteven/restaurant#1]
Hi there 👋 

I was taking a look at this project and trying to get it setup on my machine. Looks like the setup isn't valid yet. There doesn't seem to be any Entity Framework stuff setup. Is this something you're looking to add in the future?

```
dotnet restore
dotnet ef database update -Context ApplicationDbContext
dotnet ef database update -Context IdentityContext
dotnet run (OR) Run the Solution using Visual Studio 2019
```

When building I add to my own `appsettings.json` file (rightly so, because you don't want to expose and settings/keys you may have). However, it seemed to be loading the `appsettings.prod.json` 
https://github.com/emmysteven/restaurant/blob/245b7ad77356d2091dea0deeed9497a36c979351/WebUI/appsettings.prod.json#L3
and the `Serilog.Sinks.ColoredConsole` doesn't exist. 

I was able to correct some of these issue, but then ran into issues loading the JWT tokens, as it seems to be referencing them from config files.
https://github.com/emmysteven/restaurant/blob/245b7ad77356d2091dea0deeed9497a36c979351/Infrastructure/ServiceExtension.cs#L74-L97

I'd be happy to help walk you through fixing some of these issues. It may be a good idea, to pull this project down fresh and see what's missing. It's easy to get things set up on our local machine, and then when it gets shared you don't remember what all you did to set it up.  Let me know if you have any thoughts/questions.  

If that's not what you intended this project to be, feel free to close this issue 😄

**Comment by emmysteven** [comment]
My bad, the preview is not yet out, I'll comment that out from the readme file
When I tried adding appsettings.json, GitGuardian was bugging me with complaints of me exposing app secretes

I'll add the missing files, since it is an open source project
Thanks a lot!

**Comment by emmysteven** [comment]
I have removed Serilog.Sinks.ColoredConsole from appsetting.prod.json
